# Generated by Django 4.2.3 on 2023-07-07 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0005_alter_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('purpose', models.CharField(choices=[('Support', 'Support'), ('Request Custom Poster', 'Request Custom Poster'), ('Returns', 'Returns')], default='Support', max_length=30)),
                ('subject', models.TextField()),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Pending', 'Pending'), ('Complete', 'Complete')], default='Open', max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Hip-Hop/Rap', 'Hip-Hop/Rap'), ('R&B/Soul', 'R&B/Soul'), ('Pop', 'Pop'), ('Dance', 'Dance')], default='Hip-Hop/Rap', max_length=19),
        ),
    ]
