# Generated by Django 4.2.3 on 2023-07-07 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_contactrequest_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactrequest',
            name='subject',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
