# Generated by Django 4.2.3 on 2023-07-07 23:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0008_alter_contactrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactrequest',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contactrequest',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
